"""
[SKILL_ROOT]/scripts/report_doc_status.py
==========================================

Purpose:
    Generates documentation status report from oracle_forms_manifest.json.
    Tracks Enriched vs Stub vs Missing documentation coverage.

Output:
    - [PROJECT_ROOT]/legacy-system/oracle-forms-overviews/documentation_status_report.md

Usage:
    python [SKILL_ROOT]/scripts/report_doc_status.py
"""
import json
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent.resolve()

def _find_project_root() -> Path:
    """Walk up from script to find project root (sentinel: skills-lock.json or .git)."""
    for parent in SCRIPT_DIR.parents:
        if (parent / 'skills-lock.json').exists() or (parent / '.git').exists():
            return parent
    raise RuntimeError(f"Could not find project root from {__file__}")

PROJECT_ROOT = _find_project_root()
BASE_DIR = PROJECT_ROOT / 'legacy-system'

MANIFEST_PATH = BASE_DIR / 'oracle-forms-overviews' / 'oracle_forms_manifest.json'

def main():
    if not MANIFEST_PATH.exists():
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        return

    with open(MANIFEST_PATH, 'r', encoding='utf-8') as f:
        manifest = json.load(f)

    enriched = [x['ObjectID'] for x in manifest if x['DocumentationStatus'] == 'Enriched']
    stubs = [x['ObjectID'] for x in manifest if x['DocumentationStatus'] == 'Stub']
    missing = [x['ObjectID'] for x in manifest if x['DocumentationStatus'] == 'Missing']

    report_md_path = BASE_DIR / 'oracle-forms-overviews' / 'documentation_status_report.md'

    report_content = f"""# Oracle Forms Documentation Status Report

## Summary
- **Total In-Scope:** {len(manifest)}
- **Enriched:** {len(enriched)}
- **Stubs:** {len(stubs)}
- **Missing:** {len(missing)}

## Outstanding Stubs
The following {len(stubs)} modules are currently documented as stubs and require functional enrichment from legacy documentation:

{", ".join(sorted(stubs))}

---
*Generated by `scripts/documentation/report_doc_status.py`*
"""

    print("--- Oracle Forms Documentation Status Report ---")
    print(f"Total In-Scope: {len(manifest)}")
    print(f"Enriched:      {len(enriched)}")
    print(f"Stubs:         {len(stubs)}")
    print(f"Missing:       {len(missing)}")
    print("-" * 48)
    
    if stubs:
        print("Stub List (Comma Separated):")
        print(", ".join(sorted(stubs)))
    
    with open(report_md_path, 'w', encoding='utf-8') as f:
        f.write(report_content)
    print(f"\nMarkdown report generated at: {report_md_path}")

if __name__ == "__main__":
    main()
