#!/usr/bin/env python3
"""
Menu Query Tool - Interactive Menu Inventory Explorer
======================================================

Purpose:
    Queries the generated menu_inventory.json to find specific menu items,
    filter by role, or simulate the exact menu tree a user would see.

Input:
    - legacy-system/reference-data/inventories/menu_inventory.json
      (Generated by menu_builder.py)

Output:
    - Console output or JSON showing matching menu items

Key Features:
    - Query by application (--app AppFour)
    - Query by role (--role APP2_CLERK)
    - Query by item ID (--item FORM0000)
    - Simulate full menu tree (--simulate)

Example Output:
    {
      "item": "FORM0000",
      "label": "Criminal Inquiry",
      "visible_to": ["APP2_COURTS_CLERK", "APP2_SYSADMIN"],
      "enabled_for": ["APP2_SYSADMIN"]
    }

Usage:
    python menu_query.py --app AppFour --role APP2_CLERK
    python menu_query.py --item FORM0000
    python menu_query.py --app AppFour --simulate --role APP2_SYSADMIN

Related:
    - menu_builder.py: Generates the inventory this tool queries
    - ADR-0002: Menu Configuration as Code
"""

import sys
import json
import argparse
from pathlib import Path
from pathlib import Path

# Add script dir for imports
SCRIPT_DIR = Path(__file__).parent.resolve()
sys.path.append(str(SCRIPT_DIR))

from menu_builder import MenuBuilder

def simulate_role_access(nodes, role):
    """
    Simulates exact UI rendering for a specific role.
    Applies:
    1. Intersection Rule: Visible = (Legacy Visible) AND (Legacy Enabled)
    2. Hierarchical Hiding: Remove containers with no children.
    """
    simulated_nodes = []
    
    for node in nodes:
        # 1. Determine Item Permission
        legacy_visible = node.get("roles", {}).get("visible", [])
        legacy_enabled = node.get("roles", {}).get("enabled", [])
        
        # Intersection Rule logic
        
        # 1. VISIBILITY CHECK
        # If list is empty -> Default Open (True)
        # If "*" in list -> Open (True)
        # Else -> Check strict membership
        if not legacy_visible:
             can_see_legacy = True
        else:
             can_see_legacy = role in legacy_visible or ("*" in legacy_visible)
             
        # 2. ENABLEMENT CHECK
        if not legacy_enabled:
             can_click_legacy = True
        else:
             can_click_legacy = role in legacy_enabled or ("*" in legacy_enabled)
        
        # Modern Visibility Decision
        # If enabled lists exist, we enforce intersection. If lists are empty/star, we allow.
        # Logic: If I see it but can't click it -> HIDDEN (unless strict read-only exception)
        
        # For Containers (Sections/Submenus), enablement is derived from children, 
        # BUT initially we check if they are explicitly restricted.
        
        is_node_visible = can_see_legacy 
        
        # Processing Children First (Bottom-Up for Hierarchical Hiding)
        children = node.get("children") or node.get("items")
        simulated_children = []
        if children:
            simulated_children = simulate_role_access(children, role)
        
        # 2. Hierarchical Hiding Rule
        # If it's a container (has children structure) but simulated_children is empty -> HIDE
        if (children is not None) and (not simulated_children):
            is_node_visible = False
            
        # 3. Leaf Node Logic (Intersection Rule Enforced)
        if not children:
            # It's a leaf (MenuItem). 
            # If visible but not enabled -> HIDE
            if can_see_legacy and not can_click_legacy:
                is_node_visible = False
        
        if is_node_visible:
            new_node = {
                "id": node["id"],
                "label": node.get("label") or node.get("name"),
                "type": node.get("itemType") or node.get("sectionType"),
                "children": simulated_children,
                "status": "Enabled" if can_click_legacy else "ViewOnly",
                "action": node.get("action")
            }
            simulated_nodes.append(new_node)
            
    return simulated_nodes

def print_tree(nodes, prefix=""):
    for i, node in enumerate(nodes):
        is_last = i == len(nodes) - 1
        connector = "└── " if is_last else "├── "
        
        icon = "📂" if node["children"] else "🔹"
        status = "" if node["children"] else f"[{node['status']}]"
        
        action = f" -> {node['action']}" if node.get('action') else ""
        print(f"{prefix}{connector}{icon} {node['label']} ({node['id']}) {status}{action}")
        
        if node["children"]:
            extension = "    " if is_last else "│   "
            print_tree(node["children"], prefix + extension)

def main():
    parser = argparse.ArgumentParser(description="Query Menu Inventory")
    parser.add_argument("--app", help="Application Code (APP2, APP3, etc.)")
    parser.add_argument("--role", help="Filter by User Role")
    parser.add_argument("--form", help="Check overrides for specific Form")
    parser.add_argument("--item", help="Search for item by ID or Label")
    parser.add_argument("--json", action="store_true", help="Output JSON")
    parser.add_argument("--simulate", action="store_true", help="Simulate exact UI tree (Intersection + Hierarchy)")
    
    args = parser.parse_args()
    
    mb = MenuBuilder()
    inventory = mb.load_inventory()
    
    if not inventory.get("applications"):
        print("❌ Inventory empty. Run 'plugins/legacy system/inventory-manager/skills/inventory-manager/scripts/menu_inventory_generator.py' first.")
        return

    # Mode 1: Search Item
    if args.item:
        print(f"🔍 Searching for '{args.item}'...")
        results = []
        apps_to_search = [args.app] if args.app else inventory["applications"].keys()
        
        for app in apps_to_search:
            if app not in inventory["applications"]: continue
            sections = inventory["applications"][app].get("sections", [])
            found = search_by_id(sections, args.item)
            for f in found:
                f['app'] = app
                results.append(f)
        
        if args.json:
            print(json.dumps(results, indent=2))
        else:
            for r in results:
                print(f"[{r['app']}] {r['path']} ({r['id']})")
                visible = r['roles'].get('visible', [])
                print(f"   Visible to: {len(visible)} roles")
        return

    # Mode 2: Browse/Filter/Simulate
    if args.app and args.role:
        app_data = inventory["applications"].get(args.app)
        if not app_data:
            print(f"❌ Application {args.app} not found.")
            return

        sections = app_data.get("sections", [])

        if args.simulate:
            print(f"�️  SIMULATING UI for {args.role} in {args.app} ...")
            print(f"   (Applying Intersection Rule & Hierarchical Hiding)\n")
            
            sim_tree = simulate_role_access(sections, args.role)
            
            if args.json:
                print(json.dumps(sim_tree, indent=2))
            else:
                if not sim_tree:
                    print("🚫 No items visible for this role.")
                else:
                    print_tree(sim_tree)
            
        else:
            # Raw list logic
            print(f"👤 Menu for {args.role} in {args.app} (Raw List)...")
            visible_items = traverse_and_filter(sections, args.role, args.form)
            
            if args.json:
                print(json.dumps(visible_items, indent=2))
            else:
                for item in visible_items:
                    status = "✅" if item['enabled'] else "⛔"
                    print(f"{status} {item['label']} ({item['id']})")
                
    else:
        print("⚠️  Provide --item to search OR --app and --role to traverse.")

if __name__ == "__main__":
    main()
