#!/usr/bin/env python3
"""
Spec Kitty Workflow Sync
========================

Synchronizes fresh workflows from .windsurf/workflows (generated by spec-kitty init)
into the plugin's commands directory for distribution via the Bridge.

Assumptions:
1. User has installed the 'spec-kitty' CLI: `pip install --upgrade spec-kitty-cli`
2. User has initialized the repository: `spec-kitty init . --ai windsurf`
3. Run this script to propagate updates from .windsurf -> plugins -> .agent/.github

Usage:
    python3 plugins/spec-kitty/skills/spec-kitty-agent/scripts/sync_workflows.py
"""

import shutil
import os
from pathlib import Path
from typing import NoReturn

# Paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent.parent
ROOT = PROJECT_ROOT
SOURCE_DIR = ROOT / ".windsurf/workflows"
DEST_DIR = ROOT / "plugins/spec-kitty/commands"
LEGACY_WORKFLOWS_DIR = ROOT / "plugins/spec-kitty/workflows"

def sync_workflows() -> None:
    """
    Syncs workflow files from the Windsurf source directory to the plugin commands directory.
    
    This function:
    1. Reads .md files from .windsurf/workflows
    2. Renames them to remove 'spec-kitty.' prefix (to avoid double-prefixing by Bridge)
    3. Copies them to plugins/spec-kitty/commands/
    4. Removes the stale plugins/spec-kitty/workflows/ directory if present
    """
    if not SOURCE_DIR.exists():
        print(f"❌ Source not found: {SOURCE_DIR}")
        return

    print(f"🔄 Syncing workflows from {SOURCE_DIR} to {DEST_DIR}...")
    
    DEST_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Copy and Rename
    count = 0
    for src_file in SOURCE_DIR.glob("*.md"):
        # Rename strategy: spec-kitty.plan.md -> plan.md
        new_name = src_file.name
        
        # Remove prefix if present to avoid double prefix in Bridge
        if new_name.startswith("spec-kitty."):
             new_name = new_name.replace("spec-kitty.", "")
             
        dest_file = DEST_DIR / new_name
        
        print(f"   - {src_file.name} -> {new_name}")
        shutil.copy2(src_file, dest_file)
        count += 1

    print(f"✅ Synced {count} workflows.")

    # 2. Cleanup Legacy Dir if exists
    if LEGACY_WORKFLOWS_DIR.exists():
        print(f"🗑️  Removing legacy workflows dir: {LEGACY_WORKFLOWS_DIR}")
        shutil.rmtree(LEGACY_WORKFLOWS_DIR)

    print("\n⚠️  NEXT STEP: Propagate to Agents")
    print("   Run: python plugins/plugin-manager/skills/plugin-manager/scripts/bridge_installer.py --plugin plugins/spec-kitty")

if __name__ == "__main__":
    sync_workflows()
